### PR TITLE
Support the faster group api

### PR DESCRIPTION
**Pull request by aermakov-zalando**
Instead of using `/accounts/aws`, use the `/groups` API, which is 10x-15x faster for most of the users.

### CODE REVIEW

**Comment by aermakov-zalando** [comment]
Current:

    $ time zcurl -s -o /dev/null http://localhost:8080/aws-account-roles/…
    curl -H "Authorization: Bearer $(ztoken)" -s -o /dev/null   0.01s user 0.01s system 0% cpu 11.453 total
    $ time zcurl -s -o /dev/null http://localhost:8080/aws-account-roles/…
    curl -H "Authorization: Bearer $(ztoken)" -s -o /dev/null   0.01s user 0.01s system 0% cpu 10.266 total

Updated:

    $ time zcurl -s -o /dev/null http://localhost:8080/aws-account-roles/…
    curl -H "Authorization: Bearer $(ztoken)" -s -o /dev/null   0.01s user 0.01s system 1% cpu 0.960 total
    $ time zcurl -s -o /dev/null http://localhost:8080/aws-account-roles/…
    curl -H "Authorization: Bearer $(ztoken)" -s -o /dev/null   0.01s user 0.01s system 1% cpu 0.913 total

**Comment by mikkeloscar** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
👍

**Comment by njuettner** [comment]
👍

**Pull request merged**
