### PR TITLE
Update swagger to OpenAPI 3.x to fix XSS vulnerability

### PR DESCRIPTION
**Pull request by demonCoder95**
The current swagger UI is vulnerable to XSS as reported on collibra. 

You can try the script injection through this URL
https://aws-credentials.stups.zalan.do/ui/?url=https://gist.githubusercontent.com/ilima-nvps/a8cb59bbae345b413f9467edab45f641/raw/3881fb029b6f8550073d14300fb5553b77367931/swagger-xss-test

This updates the swagger version to fix that. The updated version has been tested and is safe from the vulnerability.

### CODE REVIEW

**Comment by demonCoder95** [comment]
One thing to note, the new version publishes the specification at `{base_url}/openapi.json` instead of `{base_url}/swagger.json` so will have to modify the path for the `readinessProbe` when the change is rolled out, see [here](https://github.bus.zalan.do/teapot/aws-credentials-service-deploy/blob/master/deploy/apply/stackset.yaml#L50).

**Comment by linki** [comment]
My first thought was: "Why is that thing even public? Let's not do that." But then I think it's probably used by, e.g. the API discovery tool? If so, then we should double check with them that changing the path to `/openapi.json` is fine (unless you have already confirmed that).

**Comment by linki** [comment]
LGTM

**Comment by demonCoder95** [comment]
> 

Where can I reach out to them? I haven't confirmed with API discovery, just confirmed that we depend on this file as a readiness probe.

**Comment by demonCoder95** [comment]
Okay, so they replied. The API publication depends on placement of `swagger.yaml` into `/zalando-apis/` directory in the container, docs [here](https://cloud.docs.zalando.net/howtos/api-publishing/). That's not changing, as you can check in the Dockerfile [here](https://github.com/zalando-stups/aws-credentials-service/blob/master/Dockerfile#LL11C12-L11C12). 

So, we can move forward with this change.

**Comment by demonCoder95** [comment]
👍

**Comment by linki** [comment]
👍

**Pull request merged**
